export const CATEGORIAS_LOJA = [
  "Formatura infantil e juvenil",
  "Conjuntos femininos",
  "Conjuntos masculinos",
  "Blusas masculinas",
  "Blusas femininas",
  "Vestidos/ macaquitos",
  "Calça e short masculino",
  "Calça e short feminino",
  "Moda praia",
  "Bonés Feminino e masculino",
  "Calçados baby masculinos",
  "Calçados Baby femininos",
  "Bolsas",
  "Modelo adulto",
  "Moda íntima /meias",
  "Espaço do Bebê",
  "Fitness",
  "Brinquedos",
  "Temáticos",
];
